project_name: gocontentful

release:
  github:
    owner: foomo
    name: gocontentful
  prerelease: auto

builds:
  - binary: gocontentful
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    goarm:
      - '7'
    env:
      - CGO_ENABLED=0
    main: ./main.go
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.VERSION={{.Version}}

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

changelog:
  use: github-native

brews:
  - repository:
      owner: foomo
      name: homebrew-tap
    caveats: "gocontentful -h"
    homepage: "https://github.com/foomo/gocontentful"
    description: "An Contentful Entry-Reference Mapper for Go"
    test: |
      system "#{bin}/gocontentful --version"
